<?php
/**
 *
 * Register band custom post type
 *
 * @link http://generatewp.com/post-type/
 *
 */
function band_post_type() {
	$labels = array(
		'name'                => __( 'Bands' ),
		'singular_name'       => __( 'Band' ),
		'menu_name'           => __( 'Bands' ),
		'parent_item_colon'   => __( 'Parent Item:' ),
		'all_items'           => __( 'All Bands' ),
		'view_item'           => __( 'View Band' ),
		'add_new_item'        => __( 'Add New Band' ),
		'add_new'             => __( 'Add New' ),
		'edit_item'           => __( 'Edit Band' ),
		'update_item'         => __( 'Update Band' ),
		'search_items'        => __( 'Search Band' ),
		'not_found'           => __( 'Band not found' ),
		'not_found_in_trash'  => __( 'Band not found in Trash' ),
	);
	$rewrite = array(
		'slug'                => 'band',
		'with_front'          => true,
		'pages'               => true,
		'feeds'               => true,
	);
	$args = array(
		'labels'              => $labels,
		'supports'            => array( 'title', 'revisions', 'thumbnail', ),
		'hierarchical'        => false,
		'public'              => true,
		'show_ui'             => true,
		'show_in_menu'        => true,
		'show_in_nav_menus'   => true,
		'show_in_admin_bar'   => true,
		'menu_position'       => 5,
		'can_export'          => true,
		'has_archive'         => true,
		'exclude_from_search' => false,
		'publicly_queryable'  => true,
		'rewrite'             => $rewrite,
		'capability_type'     => 'post',
	);
	register_post_type( 'band', $args );
}
add_action( 'init', 'band_post_type', 0 );


/**
 *
 * Register custom fields for band post type
 *
 * @link http://advancedcustomfields.com
 *
 */
if( function_exists('register_field_group') ) {
register_field_group(array (
	'key'                       => 'group_band_details',
	'title'                     => 'Band Details',
	'fields'                    => array (
		array (
			'key'                   => 'field_general_tab',
			'label'                 => 'General',
			'name'                  => '',
			'prefix'                => '',
			'type'                  => 'tab',
			'instructions'          => '',
			'required'              => 0,
			'conditional_logic'     => 0,
		),
		array (
			'key'                   => 'field_signing_date',
			'label'                 => 'Signing Date',
			'name'                  => 'signing_date',
			'prefix'                => '',
			'type'                  => 'date_picker',
			'instructions'          => '',
			'required'              => 0,
			'conditional_logic'     => 0,
			'display_format'        => 'F j, Y',
			'return_format'         => 'F j, Y',
			'first_day'             => 1,
		),
		array (
			'key'                   => 'field_band_genre',
			'label'                 => 'Genre',
			'name'                  => 'genre',
			'prefix'                => '',
			'type'                  => 'text',
			'instructions'          => '',
			'required'              => 0,
			'conditional_logic'     => 0,
			'default_value'         => '',
			'placeholder'           => '',
			'prepend'               => '',
			'append'                => '',
			'maxlength'             => '',
			'readonly'              => 0,
			'disabled'              => 0,
		),
		array (
			'key'                   => 'field_line_up',
			'label'                 => 'Line Up',
			'name'                  => 'line_up',
			'prefix'                => '',
			'type'                  => 'repeater',
			'instructions'          => '',
			'required'              => 0,
			'conditional_logic'     => 0,
			'min'                   => '',
			'max'                   => '',
			'layout'                => 'row',
			'button_label'          => 'Add Member',
			'sub_fields'            => array (
				array (
					'key'               => 'field_member_name',
					'label'             => 'Name',
					'name'              => 'member_name',
					'prefix'            => '',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'column_width'      => '',
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
					'readonly'          => 0,
					'disabled'          => 0,
				),
				array (
					'key'               => 'field_member_instrument',
					'label'             => 'Instrument',
					'name'              => 'member_instrument',
					'prefix'            => '',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'column_width'      => '',
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
					'readonly'          => 0,
					'disabled'          => 0,
				),
			),
		),
		array (
			'key'                   => 'field_biography',
			'label'                 => 'Biography',
			'name'                  => 'biography',
			'prefix'                => '',
			'type'                  => 'wysiwyg',
			'instructions'          => '',
			'required'              => 0,
			'conditional_logic'     => 0,
			'default_value'         => '',
			'toolbar'               => 'full',
			'media_upload'          => 1,
		),
		array (
			'key'                   => 'field_social_tab',
			'label'                 => 'Social',
			'name'                  => '',
			'prefix'                => '',
			'type'                  => 'tab',
			'instructions'          => '',
			'required'              => 0,
			'conditional_logic'     => 0,
		),
		array (
			'key'                   => 'field_links',
			'label'                 => 'Links',
			'name'                  => 'links',
			'prefix'                => '',
			'type'                  => 'repeater',
			'instructions'          => '',
			'required'              => 0,
			'conditional_logic'     => 0,
			'min'                   => '',
			'max'                   => '',
			'layout'                => 'row',
			'button_label'          => 'Add Link',
			'sub_fields'            => array (
				array (
					'key'               => 'field_website_name',
					'label'             => 'Name',
					'name'              => 'website_name',
					'prefix'            => '',
					'type'              => 'select',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'column_width'      => '',
					'choices'           => array (
						'official'        => 'Official',
						'facebook'        => 'Facebook',
						'twitter'         => 'Twitter',
						'myspace'         => 'Myspace',
						'youtube'         => 'Youtube',
						'vimeo'           => 'Vimeo',
						'dailymotion'     => 'Dailymotion',
						'instagram'       => 'Instagram',
						'tumbler'         => 'Tumbler',
						'bandcamp'        => 'Bandcamp',
						'soundcloud'      => 'Soundcloud',
						'reverbnation'    => 'Reverbnation',
					),
					'default_value'     => array (
					),
					'allow_null'        => 1,
					'multiple'          => 0,
					'ui'                => 0,
					'ajax'              => 0,
					'placeholder'       => '',
					'disabled'          => 0,
					'readonly'          => 0,
				),
				array (
					'key'               => 'field_website_url',
					'label'             => 'URL',
					'name'              => 'website_url',
					'prefix'            => '',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'column_width'      => '',
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
					'readonly'          => 0,
					'disabled'          => 0,
				),
			),
		),
		array (
			'key'                   => 'field_discography_tab',
			'label'                 => 'Discography',
			'name'                  => '',
			'prefix'                => '',
			'type'                  => 'tab',
			'instructions'          => '',
			'required'              => 0,
			'conditional_logic'     => 0,
		),
		array (
			'key'                   => 'field_releases',
			'label'                 => 'Releases',
			'name'                  => 'releases',
			'prefix'                => '',
			'type'                  => 'relationship',
			'instructions'          => '',
			'required'              => 0,
			'conditional_logic'     => 0,
			'post_type'             => array (
				0                     => 'release',
			),
			'taxonomy'              => '',
			'filters'               => array (
				0                     => 'search',
			),
			'elements'              => '',
			'max'                   => '',
			'return_format'         => 'object',
		),
		array (
			'key'                   => 'field_media_tab',
			'label'                 => 'Media',
			'name'                  => '',
			'prefix'                => '',
			'type'                  => 'tab',
			'instructions'          => '',
			'required'              => 0,
			'conditional_logic'     => 0,
		),
		array (
			'key'                   => 'field_video',
			'label'                 => 'Video',
			'name'                  => 'video',
			'prefix'                => '',
			'type'                  => 'repeater',
			'instructions'          => '',
			'required'              => 0,
			'conditional_logic'     => 0,
			'min'                   => '',
			'max'                   => '',
			'layout'                => 'row',
			'button_label'          => 'Add Video',
			'sub_fields'            => array (
				array (
					'key'               => 'field_video_url',
					'label'             => 'URL',
					'name'              => 'video_url',
					'prefix'            => '',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'column_width'      => '',
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
					'readonly'          => 0,
					'disabled'          => 0,
				),
				array (
					'key'               => 'field_video_description',
					'label'             => 'Description',
					'name'              => 'video_description',
					'prefix'            => '',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'column_width'      => '',
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
					'readonly'          => 0,
					'disabled'          => 0,
				),
			),
		),
		array (
			'key'                   => 'field_audio',
			'label'                 => 'Audio',
			'name'                  => 'audio',
			'prefix'                => '',
			'type'                  => 'repeater',
			'instructions'          => '',
			'required'              => 0,
			'conditional_logic'     => 0,
			'min'                   => '',
			'max'                   => '',
			'layout'                => 'row',
			'button_label'          => 'Add Audio',
			'sub_fields'            => array (
				array (
					'key'               => 'field_audio_url',
					'label'             => 'URL',
					'name'              => 'audio_url',
					'prefix'            => '',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'column_width'      => '',
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
					'readonly'          => 0,
					'disabled'          => 0,
				),
				array (
					'key'               => 'field_audio_description',
					'label'             => 'Description',
					'name'              => 'audio_description',
					'prefix'            => '',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'column_width'      => '',
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
					'readonly'          => 0,
					'disabled'          => 0,
				),
			),
		),
		array (
			'key'                   => 'field_other_tab',
			'label'                 => 'Other',
			'name'                  => '',
			'prefix'                => '',
			'type'                  => 'tab',
			'instructions'          => '',
			'required'              => 0,
			'conditional_logic'     => 0,
		),
		array (
			'key'                   => 'field_label',
			'label'                 => 'Label',
			'name'                  => 'label',
			'prefix'                => '',
			'type'                  => 'select',
			'instructions'          => '',
			'required'              => 0,
			'conditional_logic'     => 0,
			'choices'               => array (
				'som'                 => 'Season of Mist',
				'sua'                 => 'Underground Activists',
			),
			'default_value'         => array (
			),
			'allow_null'            => 1,
			'multiple'              => 0,
			'ui'                    => 0,
			'ajax'                  => 0,
			'placeholder'           => '',
			'disabled'              => 0,
			'readonly'              => 0,
		),
		array (
			'key'                   => 'field_territory',
			'label'                 => 'Territory',
			'name'                  => 'territory',
			'prefix'                => '',
			'type'                  => 'select',
			'instructions'          => '',
			'required'              => 0,
			'conditional_logic'     => 0,
			'choices'               => array (
				'world'               => 'World',
				'us'                  => 'North America',
				'europe'              => 'Europe',
				'france'              => 'France',
			),
			'default_value'         => array (
			),
			'allow_null'            => 1,
			'multiple'              => 0,
			'ui'                    => 0,
			'ajax'                  => 0,
			'placeholder'           => '',
			'disabled'              => 0,
			'readonly'              => 0,
		),
		array (
			'key'                   => 'field_active',
			'label'                 => 'Active',
			'name'                  => 'active',
			'prefix'                => '',
			'type'                  => 'select',
			'instructions'          => '',
			'required'              => 0,
			'conditional_logic'     => 0,
			'choices'               => array (
				'yes'                 => 'Yes',
				'no'                  => 'No',
			),
			'default_value'         => array (
			),
			'allow_null'            => 1,
			'multiple'              => 0,
			'ui'                    => 0,
			'ajax'                  => 0,
			'placeholder'           => '',
			'disabled'              => 0,
			'readonly'              => 0,
		),
	),
	'location'                  => array (
		array (
			array (
				'param'               => 'post_type',
				'operator'            => '==',
				'value'               => 'band',
			),
		),
	),
	'menu_order'                => 0,
	'position'                  => 'normal',
	'style'                     => 'default',
	'label_placement'           => 'left',
	'instruction_placement'     => 'label',
	'hide_on_screen'            => array (
		0                         => 'the_content',
		1                         => 'excerpt',
		2                         => 'custom_fields',
		3                         => 'discussion',
		4                         => 'comments',
		5                         => 'slug',
		6                         => 'author',
		7                         => 'format',
		8                         => 'page_attributes',
		9                         => 'categories',
		10                        => 'tags',
		11                        => 'send-trackbacks',
	),
));
}

?>