<?php
/**
 *
 * Register release custom post type
 *
 * @link http://generatewp.com/post-type/
 *
 */
function release_post_type() {
	$labels = array(
		'name'                => __( 'Releases' ),
		'singular_name'       => __( 'Release' ),
		'menu_name'           => __( 'Releases' ),
		'parent_item_colon'   => __( 'Parent Item:' ),
		'all_items'           => __( 'All Releases' ),
		'view_item'           => __( 'View Release' ),
		'add_new_item'        => __( 'Add New Release' ),
		'add_new'             => __( 'Add New' ),
		'edit_item'           => __( 'Edit Release' ),
		'update_item'         => __( 'Update Release' ),
		'search_items'        => __( 'Search Release' ),
		'not_found'           => __( 'Release not found' ),
		'not_found_in_trash'  => __( 'Release not found in Trash' ),
	);
	$rewrite = array(
		'slug'                => 'release',
		'with_front'          => true,
		'pages'               => true,
		'feeds'               => true,
	);
	$args = array(
		'labels'              => $labels,
		'supports'            => array( 'title', 'revisions', 'thumbnail', ),
		'hierarchical'        => false,
		'public'              => true,
		'show_ui'             => true,
		'show_in_menu'        => true,
		'show_in_nav_menus'   => true,
		'show_in_admin_bar'   => true,
		'menu_position'       => 5,
		'can_export'          => true,
		'has_archive'         => true,
		'exclude_from_search' => false,
		'publicly_queryable'  => true,
		'rewrite'             => $rewrite,
		'capability_type'     => 'post',
	);
	register_post_type( 'release', $args );
}
add_action( 'init', 'release_post_type', 0 );

/**
 *
 * Register custom fields for release post type
 *
 * @link http://advancedcustomfields.com
 *
 */
if( function_exists('register_field_group') ) {
register_field_group(array (
	'key'                           => 'group_release_details',
	'title'                         => 'Release Details',
	'fields'                        => array (
		array (
			'key'                       => 'field_general_tab',
			'label'                     => 'General',
			'name'                      => '',
			'prefix'                    => '',
			'type'                      => 'tab',
			'instructions'              => '',
			'required'                  => 0,
			'conditional_logic'         => 0,
		),
		array (
			'key'                       => 'field_catalog_number',
			'label'                     => 'Catalog Number',
			'name'                      => 'catalog_number',
			'prefix'                    => '',
			'type'                      => 'text',
			'instructions'              => '',
			'required'                  => 0,
			'conditional_logic'         => 0,
			'default_value'             => '',
			'placeholder'               => '',
			'prepend'                   => '',
			'append'                    => '',
			'maxlength'                 => '',
			'readonly'                  => 0,
			'disabled'                  => 0,
		),
		array (
			'key'                       => 'field_release_date',
			'label'                     => 'Release Date',
			'name'                      => 'release_date',
			'prefix'                    => '',
			'type'                      => 'date_picker',
			'instructions'              => '',
			'required'                  => 0,
			'conditional_logic'         => 0,
			'display_format'            => 'F j, Y',
			'return_format'             => 'F j, Y',
			'first_day'                 => 1,
		),
		array (
			'key'                       => 'field_release_date_us',
			'label'                     => 'Release Date US',
			'name'                      => 'release_date_us',
			'prefix'                    => '',
			'type'                      => 'date_picker',
			'instructions'              => '',
			'required'                  => 0,
			'conditional_logic'         => 0,
			'display_format'            => 'F j, Y',
			'return_format'             => 'F j, Y',
			'first_day'                 => 1,
		),
		array (
			'key'                       => 'field_release_genre',
			'label'                     => 'Genre',
			'name'                      => 'genre',
			'prefix'                    => '',
			'type'                      => 'text',
			'instructions'              => '',
			'required'                  => 0,
			'conditional_logic'         => 0,
			'default_value'             => '',
			'placeholder'               => '',
			'prepend'                   => '',
			'append'                    => '',
			'maxlength'                 => '',
			'readonly'                  => 0,
			'disabled'                  => 0,
		),
		array (
			'key'                       => 'field_band',
			'label'                     => 'Band',
			'name'                      => 'band',
			'prefix'                    => '',
			'type'                      => 'relationship',
			'instructions'              => '',
			'required'                  => 0,
			'conditional_logic'         => 0,
			'post_type'                 => array (
				0                         => 'band',
			),
			'taxonomy'                  => '',
			'filters'                   => array (
				0                         => 'search',
			),
			'elements'                  => '',
			'max'                       => '',
			'return_format'             => 'object',
		),
		array (
			'key'                       => 'field_tracklisting_tab',
			'label'                     => 'Tracklisting',
			'name'                      => '',
			'prefix'                    => '',
			'type'                      => 'tab',
			'instructions'              => '',
			'required'                  => 0,
			'conditional_logic'         => 0,
		),
		array (
			'key'                       => 'field_songs',
			'label'                     => 'Songs',
			'name'                      => 'songs',
			'prefix'                    => '',
			'type'                      => 'repeater',
			'instructions'              => '',
			'required'                  => 0,
			'conditional_logic'         => 0,
			'min'                       => '',
			'max'                       => '',
			'layout'                    => 'row',
			'button_label'              => 'Add Disc',
			'sub_fields'                => array (
				array (
					'key'                   => 'field_disc',
					'label'                 => 'Disc',
					'name'                  => 'disc',
					'prefix'                => '',
					'type'                  => 'repeater',
					'instructions'          => '',
					'required'              => 0,
					'conditional_logic'     => 0,
					'column_width'          => '',
					'min'                   => '',
					'max'                   => '',
					'layout'                => 'table',
					'button_label'          => 'Add Songs',
					'sub_fields'            => array (
						array (
							'key'               => 'field_song_title',
							'label'             => 'Song',
							'name'              => 'song_title',
							'prefix'            => '',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'column_width'      => '',
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
							'readonly'          => 0,
							'disabled'          => 0,
						),
					),
				),
			),
		),
		array (
			'key'                       => 'field_bonus_tracks',
			'label'                     => 'Bonus Tracks',
			'name'                      => 'bonus_tracks',
			'prefix'                    => '',
			'type'                      => 'repeater',
			'instructions'              => '',
			'required'                  => 0,
			'conditional_logic'         => 0,
			'min'                       => '',
			'max'                       => '',
			'layout'                    => 'row',
			'button_label'              => 'Add Bonus Track',
			'sub_fields'                => array (
				array (
					'key'                   => 'field_bonus_title',
					'label'                 => 'Title',
					'name'                  => 'bonus_title',
					'prefix'                => '',
					'type'                  => 'text',
					'instructions'          => '',
					'required'              => 0,
					'conditional_logic'     => 0,
					'column_width'          => '',
					'default_value'         => '',
					'placeholder'           => '',
					'prepend'               => '',
					'append'                => '',
					'maxlength'             => '',
					'readonly'              => 0,
					'disabled'              => 0,
				),
			),
		),
		array (
			'key'                       => 'field_buy_physical_tab',
			'label'                     => 'Buy Physical',
			'name'                      => '',
			'prefix'                    => '',
			'type'                      => 'tab',
			'instructions'              => '',
			'required'                  => 0,
			'conditional_logic'         => 0,
		),
		array (
			'key'                       => 'field_formats',
			'label'                     => 'Formats',
			'name'                      => 'formats',
			'prefix'                    => '',
			'type'                      => 'repeater',
			'instructions'              => '',
			'required'                  => 0,
			'conditional_logic'         => 0,
			'min'                       => '',
			'max'                       => '',
			'layout'                    => 'row',
			'button_label'              => 'Add Format',
			'sub_fields'                => array (
				array (
					'key'                   => 'field_format',
					'label'                 => 'Format',
					'name'                  => 'format',
					'prefix'                => '',
					'type'                  => 'text',
					'instructions'          => '',
					'required'              => 0,
					'conditional_logic'     => 0,
					'column_width'          => '',
					'default_value'         => '',
					'placeholder'           => '',
					'prepend'               => '',
					'append'                => '',
					'maxlength'             => '',
					'readonly'              => 0,
					'disabled'              => 0,
				),
				array (
					'key'                   => 'field_preview',
					'label'                 => 'Preview',
					'name'                  => 'preview',
					'prefix'                => '',
					'type'                  => 'image',
					'instructions'          => '',
					'required'              => 0,
					'conditional_logic'     => 0,
					'column_width'          => '',
					'return_format'         => 'array',
					'preview_size'          => 'thumbnail',
					'library'               => 'all',
				),
				array (
					'key'                   => 'field_shop',
					'label'                 => 'Shop',
					'name'                  => 'shop',
					'prefix'                => '',
					'type'                  => 'text',
					'instructions'          => '',
					'required'              => 0,
					'conditional_logic'     => 0,
					'column_width'          => '',
					'default_value'         => '',
					'placeholder'           => '',
					'prepend'               => '',
					'append'                => '',
					'maxlength'             => '',
					'readonly'              => 0,
					'disabled'              => 0,
				),
				array (
					'key'                   => 'field_shop_us',
					'label'                 => 'Shop US',
					'name'                  => 'shop_us',
					'prefix'                => '',
					'type'                  => 'text',
					'instructions'          => '',
					'required'              => 0,
					'conditional_logic'     => 0,
					'column_width'          => '',
					'default_value'         => '',
					'placeholder'           => '',
					'prepend'               => '',
					'append'                => '',
					'maxlength'             => '',
					'readonly'              => 0,
					'disabled'              => 0,
				),
			),
		),
		array (
			'key'                       => 'field_buy_digital_tab',
			'label'                     => 'Buy Digital',
			'name'                      => '',
			'prefix'                    => '',
			'type'                      => 'tab',
			'instructions'              => '',
			'required'                  => 0,
			'conditional_logic'         => 0,
		),
		array (
			'key'                       => 'field_bandcamp',
			'label'                     => 'Bandcamp',
			'name'                      => 'bandcamp',
			'prefix'                    => '',
			'type'                      => 'text',
			'instructions'              => '',
			'required'                  => 0,
			'conditional_logic'         => 0,
			'default_value'             => '',
			'placeholder'               => '',
			'prepend'                   => '',
			'append'                    => '',
			'maxlength'                 => '',
			'readonly'                  => 0,
			'disabled'                  => 0,
		),
		array (
			'key'                       => 'field_itunes',
			'label'                     => 'iTunes',
			'name'                      => 'itunes',
			'prefix'                    => '',
			'type'                      => 'text',
			'instructions'              => '',
			'required'                  => 0,
			'conditional_logic'         => 0,
			'default_value'             => '',
			'placeholder'               => '',
			'prepend'                   => '',
			'append'                    => '',
			'maxlength'                 => '',
			'readonly'                  => 0,
			'disabled'                  => 0,
		),
	),
	'location'                      => array (
		array (
			array (
				'param'                   => 'post_type',
				'operator'                => '==',
				'value'                   => 'release',
			),
		),
	),
	'menu_order'                    => 0,
	'position'                      => 'normal',
	'style'                         => 'default',
	'label_placement'               => 'left',
	'instruction_placement'         => 'label',
	'hide_on_screen'                => array (
		0                             => 'the_content',
		1                             => 'excerpt',
		2                             => 'custom_fields',
		3                             => 'discussion',
		4                             => 'comments',
		5                             => 'slug',
		6                             => 'author',
		7                             => 'format',
		8                             => 'page_attributes',
		9                             => 'categories',
		10                            => 'tags',
		11                            => 'send-trackbacks',
	),
));
}

?>